name: Autoupdate_China_Domain

on:
  push:
    branches:
      - development
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update domain list
      run: |
        cd ./AutoUpdate
        rm -f accelerated-domains.china.conf
        wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        rm -f gfwlist.txt
        wget https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
        python ChinaDomainlist_AutoUpdate.py	
    - name: commit
      run: |
        git checkout development
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "autoupdate" -a
        git push "https://$GH_TOKEN@$github.com/rwx9032/AdguardHome/" development:development
