name: Autoupdate_China_Domain

on:
  push:
    branches:
      - development
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update domain list
      run: |
        cd ./AutoUpdate
        rm -f accelerated-domains.china.conf
        rm -f CNDomains_AdguardHome.txt
        wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        rm -f gfwlist.txt
        rm -f gfwlist_decode.txt
        wget https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
        python ChinaDomainlist_AutoUpdate.py
        python Gfwlist_Decode.py
        rm -f gfwlist2dnsmasq.sh
        rm -f gfwlist_dnsmasq.conf
        wget https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh
        chmod +x gfwlist2dnsmasq.sh
        sh gfwlist2dnsmasq.sh -o ./gfwlist_dnsmasq.conf
        rm -f gfwlist_AdguardHome.txt
        python Gfwlist_AutoUpdate.py
        rm -f config
        cp ./CNDomains_AdguardHome.txt ./config
        cp ./gfwlist_AdguardHome.txt ./config
        cp ./head.txt ./config
        
        
    - name: commit
      env:
        GIT_NAME: github-actions[bot]
        GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        REPO: github.com/rwx9032/AdguardHome
        GH_TOKEN: ${{ secrets.GH_TOKEN_BLOG }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "autoupdate" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
